iam/iam/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path, include
from django.conf.urls.static import static
from oauth2_provider.views import TokenView, RevokeTokenView
from oauth2_provider.views.application import ApplicationRegistration, ApplicationDetail, ApplicationList
from oauth2_provider.views.introspect import IntrospectTokenView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("usermanager.urls")), # User Manager URL
    path('', include('productmanager.urls')), # Product Manager URL
    path("__reload__/", include("django_browser_reload.urls")),
    path('api/v1/', include('rest_framework.urls')),
    # path('auth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('auth/token/', TokenView.as_view(), name='token'),  # Custom token endpoint URL
    path('auth/revoke_token/', RevokeTokenView.as_view(), name='revoke-token'),  # Custom token revocation URL
    path('auth/applications/register/', ApplicationRegistration.as_view(template_name='/oauth2_provider/register_application.html'), name='register'), # Register application route
    path('auth/applications/<int:pk>/', ApplicationDetail.as_view(template_name='./oauth2_provider/application.html'), name='application_detail'), # Auth Application Detail
    path('auth/applications/', ApplicationList.as_view(), name='oauth2_provider_application_list'), # Auth Application List
    path('auth/introspect/', IntrospectTokenView.as_view(), name='introspect'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Localization URL patterns
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iam/usermanager/urls.py
from django.urls import include, path
from .geoip import GeoIPView
from . import views
from django.conf import settings

# Oauth2
import oauth2_provider.views as oauth2_views
from .views import ApiEndpoint

# OAuth2 provider endpoints
oauth2_endpoint_views = [
    path('authorize/', oauth2_views.AuthorizationView.as_view(), name="authorize"),
    path('token/', oauth2_views.TokenView.as_view(), name="token"),
    path('revoke-token/', oauth2_views.RevokeTokenView.as_view(), name="revoke-token"),
]

if settings.DEBUG:
    # OAuth2 Application Management endpoints
    oauth2_endpoint_views += [
        path('application/', oauth2_views.ApplicationList.as_view(), name="list"),
        path('application/register/', oauth2_views.ApplicationRegistration.as_view(), name="register"),
        path('application/<pk>/', oauth2_views.ApplicationDetail.as_view(), name="detail"),
        path('application/<pk>/delete/', oauth2_views.ApplicationDelete.as_view(), name="delete"),
        path('application/<pk>/update/', oauth2_views.ApplicationUpdate.as_view(), name="update")
    ]
    # OAuth2 Token Management endpoints
    oauth2_endpoint_views += [
        path('authorized-tokens/', oauth2_views.AuthorizedTokensListView.as_view(), name="authorized-token-list"),
        path('authorized-tokens/<pk>/delete/', oauth2_views.AuthorizedTokenDeleteView.as_view(), name="authorized-token-delete"),
    ]
    

urlpatterns = [
    path("", views.index, name="home" ),
    path("geoip/", GeoIPView, name="IPInfoView"),
    path('auth/', include((oauth2_endpoint_views, 'oauth2_provider'), namespace="oauth2_provider")),
    path('api/hello', ApiEndpoint.as_view()),  # an example resource endpoint
    path('secret', views.secret_page, name='secret'),
    path("account/login/", views.UserLogin, name="login"),
]

iam/templates/oauth2_provider/application_confirm_delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        <h3 class="block-center-heading">{% trans "Are you sure to delete the application" %} {{ application.name }}?</h3>
        <form method="post" action="{% url 'oauth2_provider:delete' application.pk %}">
            {% csrf_token %}

            <div class="control-group">
                <div class="controls">
                    <a class="btn btn-large" href="{% url "oauth2_provider:list" %}">{% trans "Cancel" %}</a>
                    <input type="submit" class="btn btn-large btn-danger" name="allow" value="{% trans 'Delete' %}"/>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

iam/templates/oauth2_provider/application_detail.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}

<navbar class="block mb-10">
    <div class="fixed top-0 left-0 w-full bg-gray-900 text-white py-2 px-4 flex items-center justify-between">
        <div class="flex items-center space-x-4">
            <div class="rounded-full bg-yellow-500 w-3 h-3"></div>
            <div class="rounded-full bg-red-500 w-3 h-3"></div>
            <div class="rounded-full bg-green-500 w-3 h-3 cursor-pointer transition-all duration-500" onclick="toggleFullscreen();"></div>
        </div>
        <div class="flex items-center space-x-4">
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                </svg>
                <span class="text-sm">Menu</span>
            </button>
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                <span class="text-sm">Add</span>
            </button>
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m4 0h4m-4 0v6m0 0v6m0-6h-4m0-2h4M12 4v4m0 0v4m0-4h4m2 0h-6m0-2h6M4 6h4m2 0h6m-6 0v6m0 0v2m0 2v2m0-2h2m2 0h2m0-2v-2m0-2v-2m0 2h-2m-2 0H8m2 0H8m0 2v2m0 2v2m0-2h2m2 0h2m0-2v-2m0-2v-2m0 2h-2"></path>
                </svg>
                <span class="text-sm">Settings</span>
            </button>
        </div>
    </div>
</navbar>

    <div class="w-full flex justify-center">
        <div class="border-spacing-4 border border-gray-400 bg-slate-200 shadow-md rounded-lg p-4: md:p-6">
            <h3 class="text-slate-700 text-2xl font-semibold">{{ application.name }}</h3>
            <hr class="my-4">
            <ul class="unstyled space-y-4">
                <li>
                    <p class="text-slate-700"><b>{% trans "Client id" %}</b></p>
                    <input class="input-block-level bg-gray-200 rounded-md border border-gray-300 text-slate-600" type="text" value="{{ application.client_id }}" readonly>
                </li>

                <li>
                    <p class="text-slate-700"><b>{% trans "Client secret" %}</b></p>
                    <input class="input-block-level bg-gray-200 rounded-md border border-gray-300 text-slate-600" type="text" value="{{ application.client_secret }}" readonly>
                </li>

                <li>
                    <p class="text-slate-700"><b>{% trans "Client type" %}</b></p>
                    <p class="text-slate-600">{{ application.client_type }}</p>
                </li>

                <li>
                    <p class="text-slate-800"><b>{% trans "Authorization Grant Type" %}</b></p>
                    <p class="text-slate-600">{{ application.authorization_grant_type }}</p>
                </li>

                <li>
                    <p class="text-slate-700"><b>{% trans "Redirect Uris" %}</b></p>
                    <textarea class="text-slate-600 rounded-md" readonly>{{ application.redirect_uris }}</textarea>
                </li>
            </ul>
            <hr class="my-2 bg-gray-900">
            <div class="flex justify-between space-x-4">
                <a class="hover:bg-gray-800 hover:text-slate-100 rounded-md border border-gray-500 px-4 py-2" href="{% url "oauth2_provider:list" %}">{% trans "Go Back" %}</a>
                <a class="rounded-md bg-blue-500 text-slate-100 hover:bg-blue-600 hover:shadow-md transition-all duration-300 py-2 px-4" href="{% url "oauth2_provider:update" application.id %}">{% trans "Edit" %}</a>
                <a class="rounded-md border border-red-700 hover:bg-red-700 text-red-700 hover:text-slate-100 transition-all duration-300 py-2 px-4" href="{% url "oauth2_provider:delete" application.id %}">{% trans "Delete" %}</a>
            </div>
        </div>
    </div>
{% endblock content %}

iam/templates/oauth2_provider/application_form.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
<!-- Header -->
<navbar class="block mb-10">
    <div class="fixed top-0 left-0 w-full bg-gray-900 text-white py-2 px-4 flex items-center justify-between">
        <div class="flex items-center space-x-4">
            <div class="rounded-full bg-yellow-500 w-3 h-3"></div>
            <div class="rounded-full bg-red-500 w-3 h-3"></div>
            <div class="rounded-full bg-green-500 w-3 h-3 cursor-pointer transition-all duration-500" onclick="toggleFullscreen();" title="View full screen"></div>
        </div>
        <div class="flex items-center space-x-4">
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                </svg>
                <span class="text-sm">Menu</span>
            </button>
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                <span class="text-sm">Add</span>
            </button>
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m4 0h4m-4 0v6m0 0v6m0-6h-4m0-2h4M12 4v4m0 0v4m0-4h4m2 0h-6m0-2h6M4 6h4m2 0h6m-6 0v6m0 0v2m0 2v2m0-2h2m2 0h2m0-2v-2m0-2v-2m0 2h-2m-2 0H8m2 0H8m0 2v2m0 2v2m0-2h2m2 0h2m0-2v-2m0-2v-2m0 2h-2"></path>
                </svg>
                <span class="text-sm">Settings</span>
            </button>
        </div>
    </div>
</navbar>

<div class="w-full flex justify-center justify-items-center">
    <div class="w-fit">
        <div class="border border-gray-500 md:mt-16 rounded-xl shadow-lg p-4 items-center bg-slate-200">
            <form class="form-horizontal" method="post" action="{% block app-form-action-url %}{% url 'oauth2_provider:update' application.id %}{% endblock app-form-action-url %}">
                <h3 class="block-center-heading">
                    {% block app-form-title %}
                        {% trans "Edit application" %} {{ application.name }}
                    {% endblock app-form-title %}
                </h3>
                {% csrf_token %}

                {% for field in form %}
                    <div class="control-group {% if field.errors %}error{% endif %}">
                        <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="controls">
                            {{ field }}
                            {% for error in field.errors %}
                                <span class="help-inline">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}

                <div class="control-group {% if form.non_field_errors %}error{% endif %}">
                    {% for error in form.non_field_errors %}
                        <span class="help-inline">{{ error }}</span>
                    {% endfor %}
                </div>
                <hr class="my-4">
                <div class="control-group">
                    <div class="flex justify-between w-full">
                        <a class="rounded-md px-4 py-2 hover:bg-gray-800 hover:text-slate-200 hover:shadow-md transition-colors duration-300 outline outline-offset-1 outline-gray-500" href="{% block app-form-back-url %}{% url "oauth2_provider:detail" application.id %}{% endblock app-form-back-url %}">
                            {% trans "Go Back" %}
                        </a>
                        <button type="submit" class="px-4 py-2 bg-blue-500 text-slate-100 rounded-md  hover:shadow-md hover:bg-blue-600 hover:text-slate-100 transition-colors duration-300 hover:outline hover:outline-offset-2 hover:outline-blue-800">{% trans "Save" %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

iam/templates/oauth2_provider/application_list.html
{% extends "oauth2_provider/base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<!-- Top Navbar -->
<navbar class="block mb-10">
    <div class="fixed top-0 left-0 w-full bg-gray-900 text-white py-2 px-4 flex items-center justify-between">
        <div class="flex items-center space-x-4">
            <div class="rounded-full bg-yellow-500 w-3 h-3"></div>
            <div class="rounded-full bg-red-500 w-3 h-3"></div>
            <div class="rounded-full bg-green-500 w-3 h-3 cursor-pointer transition-all duration-500" onclick="toggleFullscreen();"></div>
        </div>
        <div class="flex items-center space-x-4">
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                </svg>
                <span class="text-sm">Menu</span>
            </button>
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                <span class="text-sm">Add</span>
            </button>
            <button class="flex items-center space-x-2">
                <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m4 0h4m-4 0v6m0 0v6m0-6h-4m0-2h4M12 4v4m0 0v4m0-4h4m2 0h-6m0-2h6M4 6h4m2 0h6m-6 0v6m0 0v2m0 2v2m0-2h2m2 0h2m0-2v-2m0-2v-2m0 2h-2m-2 0H8m2 0H8m0 2v2m0 2v2m0-2h2m2 0h2m0-2v-2m0-2v-2m0 2h-2"></path>
                </svg>
                <span class="text-sm">Settings</span>
            </button>
        </div>
    </div>
</navbar>


<div class="container">
    <div class="flex justify-center">
        <div class="border border-gray-500 shadow-md rounded-lg p-4">
            <h3 class="text-2xl font-semibold text-slate-600">{% trans "Applications" %}</h3>
                <div class="rounded-lg">
                    {% if applications %}
                        <ul>
                            {% for application in applications %}
                                <li><a href="{{ application.get_absolute_url }}"><p class="border hover:bg-gray-500 hover:text-slate-100 transition-all  py-2 px-4 my-4 hover:font-medium hover:shadow-md duration-300">{{ application.name }}</p></a></li>
                            {% endfor %}
                        </ul>
                        <hr>
                        <a class="py-2 px-4 rounded-md text-slate-100 bg-blue-500 hover:bg-blue-600 hover:shadow-md" href="{% url "oauth2_provider:register" %}">
                            {% trans "New Application" %}
                        </a>
                    {% else %}

                        <p class="text-slate-500">
                            {% trans "No applications defined" %}. 
                            
                            {% trans "if you want to register a new one" %}
                        </p>
                        <hr class="w-[95%] my-4">
                        <div class="flex justify-between">
                            <a href="{% url 'home' %}" title="create new application" class="border-2S border-gray-500 rounded-md px-2 py-1 text-slate-500 hover:bg-gray-600 hover:text-slate-100 hover:rounded-md hover:border-1 transition-all duration-300">
                                {% trans "Go back" %}
                            </a> 
                            
                            <a href="{% url 'oauth2_provider:register' %}" title="create new application" class="border-1 bg-blue-500 rounded-md px-2 py-1 text-slate-100 hover:bg-blue-600 transition-all duration-300">
                                {% trans "Create new" %}
                            </a> 
                        </di>
                    {% endif %}
                </div>
        </div>
    </div>

    <!-- Menu -->

</div>
{% endblock content %}

iam/templates/oauth2_provider/application_registration_form.html
{% extends "oauth2_provider/application_form.html" %}

{% load i18n %}

{% block app-form-title %}<h2 class="text-xl">{% trans "Register a new application" %}</h2>{% endblock app-form-title %}

{% block app-form-action-url %}{% url 'oauth2_provider:register' %}{% endblock app-form-action-url %}

{% block app-form-back-url %}{% url "oauth2_provider:list" %}"{% endblock app-form-back-url %}

iam/templates/oauth2_provider/authorize.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        {% if not error %}
            <form id="authorizationForm" method="post">
                <h3 class="block-center-heading">{% trans "Authorize" %} {{ application.name }}?</h3>
                {% csrf_token %}

                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <p>{% trans "Application requires the following permissions" %}</p>
                <ul>
                    {% for scope in scopes_descriptions %}
                        <li>{{ scope }}</li>
                    {% endfor %}
                </ul>

                {{ form.errors }}
                {{ form.non_field_errors }}

                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-large" value="Cancel"/>
                        <input type="submit" class="btn btn-large btn-primary" name="allow" value="Authorize"/>
                    </div>
                </div>
            </form>

        {% else %}
            <h2>Error: {{ error.error }}</h2>
            <p>{{ error.description }}</p>
        {% endif %}
    </div>
{% endblock %}

iam/templates/oauth2_provider/authorized-token-delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>{% trans "Are you sure you want to delete this token?" %}</p>
        <input type="submit" value="{% trans 'Delete' %}" />
    </form>
{% endblock %}

iam/templates/oauth2_provider/authorized-tokens.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
    <h1>{% trans "Tokens" %}</h1>
        <ul>
        {% for authorized_token in authorized_tokens %}
            <li>
                {{ authorized_token.application }}
                (<a href="{% url 'oauth2_provider:authorized-token-delete' authorized_token.pk %}">{% trans "revoke" %}</a>)
            </li>
            <ul>
            {% for scope_name, scope_description in authorized_token.scopes.items %}
                <li>{{ scope_name }}: {{ scope_description }}</li>
            {% endfor %}
            </ul>
        {% empty %}
            <li>{% trans "There are no authorized tokens yet." %}</li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

iam/templates/oauth2_provider/base.html
<!-- templates/oauth2_provider/base.html -->
{% load static tailwind_tags %}
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
    <head>
		<title>{% block title %} {% translate "EZ Startup - Easy for Everyone" %}{% endblock %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% comment %} <rel rel="stylesheet" type="text/css" src="{% static "css/main.css" %}'> {% endcomment %}
		{% tailwind_css %}
        
        {% block stylesheet %}
           
        {% endblock %}
	</head>
<body>
    <main>
    <!-- Custom content goes here -->
    <section>
    {% block content %}
    {% endblock %}
    </section>

    <!-- Load other JavaScript files or additional tags -->
    
    <!-- Include the i18n JavaScript catalog -->
    {% block script %}
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    {% endblock %}
</main>
</body>
</html>

iam/templates/oauth2_provider/logout_confirm.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        {% if not error %}
            <form id="authorizationForm" method="post">
                {% if application %}
                    <h3 class="block-center-heading">Confirm Logout requested by {{ application.name }}</h3>
                {% else %}
                    <h3 class="block-center-heading">Confirm Logout</h3>
                {% endif %}
                {% csrf_token %}

                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                {{ form.errors }}
                {{ form.non_field_errors }}

                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-large" value="Cancel"/>
                        <input type="submit" class="btn btn-large btn-primary" name="allow" value="Logout"/>
                    </div>
                </div>
            </form>

        {% else %}
            <h2>Error: {{ error.error }}</h2>
            <p>{{ error.description }}</p>
        {% endif %}
    </div>
{% endblock %}

iam/templates/oauth2_provider/register_application_form.html
<!-- register_application.html -->
{% extends "oauth2_provider/application_form.html" %}

{% block extra_fields %}
    <!-- Add or modify extra fields here -->
    {{ block.super }}
    <!-- Additional content -->
    <h2>Hellow World</h2>
    <p>I am new </p>
{% endblock %}